Repository nttcom/metemcyber, pull requests merged in 2020-12, with the labels that each got.

#4 Topic/#3 improve readme
  README.md
Labels: documentation

#6 Topic/#5 add supplementary info
  README.md
  screenshot.png
Labels: documentation

#9 Topic/#2 create private catalog
  contracts/CTIBroker.sol
  contracts/CTICatalog.sol
  metemcyber_ctl.sh
  requirements/common.txt
  setup_demo_catalog.in
  src/client.py
  src/client_model.py
  src/client_ui.py
  src/contracts_data/CTIBroker.combined.json
  src/contracts_data/CTICatalog.combined.json
  src/contracts_data/CTIOperator.combined.json
  src/contracts_data/CTIToken.combined.json
  src/contracts_data/MetemcyberUtil.combined.json
  src/ctibroker.py
  src/cticatalog.py
  src/inventory.py
Labels: enhancement

#14 Fix arg split
  src/misp_client.py
Labels: bug

#15 change to display accepting tokens
  src/client_ui.py
  src/solver.py
Labels: enhancement

#34 Topic/read the docs
  README.md
Labels: documentation

#35 modify description
  README.md
Labels: documentation, enhancement

#41 Update catalog and broker address
  workspace.pricom/config.ini
Labels: enhancement
